---
# Production environment override
services:
  php:
    image: ${DOCKER_USERNAME:-erikweidenauer}/onlydance-ar-symfony:latest
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
